version: '3'

services:
    web:
        image: nginx
        container_name: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./web/conf.d:/etc/nginx/conf.d
            - ./web/ssl:/etc/nginx/ssl
        depends_on:
            - confluence
        networks:
            - confluence_frontend

    confluence:
        build:
            context: ./confluence
            args:
                CONFLUENCE_VERSION: 7.3.4
                PROXY_NAME: localhost
        image: confluence
        container_name: confluence
        depends_on:
            - postgres
        volumes:
            - confluence_app_volume:/var/atlassian/application-data/confluence
        networks:
            - confluence_frontend
            - confluence_backend

    postgres:
        image: postgres:12-alpine
        container_name: psql
        environment:
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - POSTGRES_DB
        volumes:
            - confluence_db_volume:/var/lib/postgresql/data
        networks:
            - confluence_backend

volumes:
    confluence_app_volume:
    confluence_db_volume:

networks:
    confluence_frontend:
    confluence_backend:
